"""Fontes DATASUS via PySUS com specs manuais (SINAN, SIM, SIH)."""

from datetime import datetime
from typing import List

from guaraci.core.contracts import SourceParameterSpec
from guaraci.services import downloads as _downloads
from guaraci.services.downloads import (
    EXPORT_FORMAT_VALUES,
    DownloadSource,
    PysusDownloadSource,
    SourceDescriptor,
)
from guaraci.services.normalizers import (
    _normalize_sih_params,
    _normalize_sim_params,
    _normalize_sinan_params,
)
from guaraci.utils.mapping import UF_DICT


def build_sources() -> List[DownloadSource]:
    """Retorna as fontes PySUS manuais na ordem canonica."""
    current_year = datetime.now().year
    last_year = current_year - 1
    uf_values = sorted(set(UF_DICT.values()))
    return [
        PysusDownloadSource(
            descriptor=SourceDescriptor(
                source="sinan",
                title="SINAN",
                mode="pysus ftp",
            ),
            datasource_cls=_downloads.SinanDataSource,
            params_schema=[
                SourceParameterSpec(
                    name="output_dir",
                    phase="tecnica",
                    param_type="string",
                    description="Output directory for downloaded files.",
                    required=False,
                    default=None,
                ),
                SourceParameterSpec(
                    name="output_format",
                    phase="exportacao",
                    param_type="string",
                    description="Optional export format for processed datasets.",
                    required=False,
                    default=None,
                    allowed_values=EXPORT_FORMAT_VALUES,
                ),
                SourceParameterSpec(
                    name="start_year",
                    phase="coleta",
                    param_type="integer",
                    description="Starting year for file discovery.",
                    required=True,
                    default=last_year,
                    minimum=1990,
                    maximum=current_year,
                ),
                SourceParameterSpec(
                    name="end_year",
                    phase="coleta",
                    param_type="integer",
                    description="Ending year for file discovery.",
                    required=True,
                    default=last_year,
                    minimum=1990,
                    maximum=current_year,
                ),
                SourceParameterSpec(
                    name="diseases",
                    phase="coleta",
                    param_type="string_list",
                    description="Disease code list to download.",
                    required=False,
                    default=list(_downloads.SinanDataSource.NEGLECTED_DISEASES),
                    allowed_values=list(_downloads.SinanDataSource.NEGLECTED_DISEASES),
                ),
                SourceParameterSpec(
                    name="uf",
                    phase="refinamento",
                    param_type="string",
                    description="Optional UF filter for exported dataset.",
                    required=False,
                    default=None,
                    allowed_values=uf_values,
                ),
                SourceParameterSpec(
                    name="municipio",
                    phase="refinamento",
                    param_type="string",
                    description="Optional municipality name filter for export.",
                    required=False,
                    default=None,
                ),
                SourceParameterSpec(
                    name="sexo",
                    phase="refinamento",
                    param_type="string",
                    description="Optional sex filter for export.",
                    required=False,
                    default=None,
                    allowed_values=["M", "F"],
                ),
                SourceParameterSpec(
                    name="faixa_etaria",
                    phase="refinamento",
                    param_type="string",
                    description="Optional age-band code filter for export.",
                    required=False,
                    default=None,
                ),
                SourceParameterSpec(
                    name="evolucao",
                    phase="refinamento",
                    param_type="string",
                    description="Optional case evolution filter for export.",
                    required=False,
                    default=None,
                ),
                SourceParameterSpec(
                    name="classificacao",
                    phase="refinamento",
                    param_type="string",
                    description="Optional classification filter for export.",
                    required=False,
                    default=None,
                ),
            ],
            normalize_params=_normalize_sinan_params,
        ),
        PysusDownloadSource(
            descriptor=SourceDescriptor(
                source="sim",
                title="SIM",
                mode="pysus ftp",
            ),
            datasource_cls=_downloads.SimDataSource,
            params_schema=[
                SourceParameterSpec(
                    name="output_dir",
                    phase="tecnica",
                    param_type="string",
                    description="Output directory for downloaded files.",
                    required=False,
                    default=None,
                ),
                SourceParameterSpec(
                    name="output_format",
                    phase="exportacao",
                    param_type="string",
                    description="Optional export format for processed datasets.",
                    required=False,
                    default=None,
                    allowed_values=EXPORT_FORMAT_VALUES,
                ),
                SourceParameterSpec(
                    name="start_year",
                    phase="coleta",
                    param_type="integer",
                    description="Starting year for file discovery.",
                    required=True,
                    default=last_year,
                    minimum=1979,
                    maximum=current_year,
                ),
                SourceParameterSpec(
                    name="end_year",
                    phase="coleta",
                    param_type="integer",
                    description="Ending year for file discovery.",
                    required=True,
                    default=last_year,
                    minimum=1979,
                    maximum=current_year,
                ),
                SourceParameterSpec(
                    name="groups",
                    phase="coleta",
                    param_type="string_list",
                    description="SIM groups to download.",
                    required=False,
                    default=list(_downloads.SimDataSource.DEFAULT_GROUPS),
                    allowed_values=list(_downloads.SimDataSource.ALL_GROUPS),
                ),
                SourceParameterSpec(
                    name="states",
                    phase="coleta",
                    param_type="string_list",
                    description="UF filter list.",
                    required=False,
                    default=None,
                    allowed_values=uf_values,
                ),
                SourceParameterSpec(
                    name="uf",
                    phase="refinamento",
                    param_type="string",
                    description="Optional UF filter for exported dataset.",
                    required=False,
                    default=None,
                    allowed_values=uf_values,
                ),
                SourceParameterSpec(
                    name="municipio",
                    phase="refinamento",
                    param_type="string",
                    description="Optional municipality filter for export.",
                    required=False,
                    default=None,
                ),
                SourceParameterSpec(
                    name="sexo",
                    phase="refinamento",
                    param_type="string",
                    description="Optional sex filter for export.",
                    required=False,
                    default=None,
                    allowed_values=["M", "F"],
                ),
                SourceParameterSpec(
                    name="causa_basica",
                    phase="refinamento",
                    param_type="string",
                    description="Optional basic cause filter for export.",
                    required=False,
                    default=None,
                ),
                SourceParameterSpec(
                    name="ano_obito",
                    phase="refinamento",
                    param_type="integer",
                    description="Optional year-of-death filter for export.",
                    required=False,
                    default=None,
                    minimum=1979,
                    maximum=current_year,
                ),
            ],
            normalize_params=_normalize_sim_params,
        ),
        PysusDownloadSource(
            descriptor=SourceDescriptor(
                source="sih",
                title="SIH",
                mode="pysus ftp",
            ),
            datasource_cls=_downloads.SihDataSource,
            params_schema=[
                SourceParameterSpec(
                    name="output_dir",
                    phase="tecnica",
                    param_type="string",
                    description="Output directory for downloaded files.",
                    required=False,
                    default=None,
                ),
                SourceParameterSpec(
                    name="output_format",
                    phase="exportacao",
                    param_type="string",
                    description="Optional export format for processed datasets.",
                    required=False,
                    default=None,
                    allowed_values=EXPORT_FORMAT_VALUES,
                ),
                SourceParameterSpec(
                    name="start_year",
                    phase="coleta",
                    param_type="integer",
                    description="Starting year for file discovery.",
                    required=True,
                    default=last_year,
                    minimum=1979,
                    maximum=current_year,
                ),
                SourceParameterSpec(
                    name="end_year",
                    phase="coleta",
                    param_type="integer",
                    description="Ending year for file discovery.",
                    required=True,
                    default=last_year,
                    minimum=1979,
                    maximum=current_year,
                ),
                SourceParameterSpec(
                    name="groups",
                    phase="coleta",
                    param_type="string_list",
                    description="SIH groups to download. Leave empty to include all groups.",
                    required=False,
                    default=None,
                    allowed_values=list(_downloads.SihDataSource.ALL_GROUPS),
                ),
                SourceParameterSpec(
                    name="states",
                    phase="coleta",
                    param_type="string_list",
                    description="UF filter list.",
                    required=False,
                    default=None,
                    allowed_values=uf_values,
                ),
                SourceParameterSpec(
                    name="months",
                    phase="coleta",
                    param_type="string_list",
                    description="Month list (1-12). Leave empty to include all months.",
                    required=False,
                    default=None,
                    allowed_values=[str(item) for item in range(1, 13)],
                ),
                SourceParameterSpec(
                    name="uf",
                    phase="refinamento",
                    param_type="string",
                    description="Optional UF filter for exported dataset.",
                    required=False,
                    default=None,
                    allowed_values=uf_values,
                ),
                SourceParameterSpec(
                    name="municipio",
                    phase="refinamento",
                    param_type="string",
                    description="Optional municipality filter for export.",
                    required=False,
                    default=None,
                ),
                SourceParameterSpec(
                    name="sexo",
                    phase="refinamento",
                    param_type="string",
                    description="Optional sex filter for export.",
                    required=False,
                    default=None,
                    allowed_values=["M", "F"],
                ),
            ],
            normalize_params=_normalize_sih_params,
        ),
    ]
