"""
Shared read/write/render helpers for the Guaraci data dictionary.

Used by scripts/sample_sources.py to keep guaraci/data/field_dictionary.json
(machine-readable) and docs/DATA_DICTIONARY.md (human-readable) generated by
the exact same code path, so they never drift apart the way they did when the
promotion from reports/ to these two files was a manual copy/reformat step.
"""
from __future__ import annotations

import json
import os
from pathlib import Path
from typing import Any, Dict

from guaraci.utils.atomic_io import replace_with_retry


def load_field_dictionary(path: Path) -> Dict[str, Dict[str, Any]]:
    """Load the versioned field dictionary. Returns {} if the file doesn't exist yet."""
    if not path.exists():
        return {}
    with path.open("r", encoding="utf-8") as fh:
        return json.load(fh)


def atomic_write_json(path: Path, data: Dict[str, Any]) -> None:
    """Write JSON atomically: write to a .tmp sibling, then os.replace() over the target.

    Guarantees the versioned dictionary is never left half-written if the
    process is interrupted mid-write.
    """
    path.parent.mkdir(parents=True, exist_ok=True)
    tmp_path = path.with_suffix(path.suffix + ".tmp")
    tmp_path.write_text(json.dumps(data, indent=2, ensure_ascii=False, sort_keys=True), encoding="utf-8")
    replace_with_retry(tmp_path, path)


def _format_status_line(source: str, entry: Dict[str, Any]) -> str:
    status = entry.get("status", "unknown")
    if status == "ok":
        rows = entry.get("rows_sampled")
        suffix = f" ({rows} rows sampled)" if rows is not None else ""
        return f"- **Status:** ok{suffix}"
    return f"- **Status:** {status}"


def _format_filters_line(entry: Dict[str, Any]) -> str:
    filters = entry.get("filters") or []
    if isinstance(filters, dict) and "error" in filters:
        return f"- **Filters:** (schema error: {filters['error']})"
    rendered = ", ".join(f"`{name}`" for name in filters)
    return f"- **Filters:** {rendered}" if rendered else "- **Filters:** (none)"


def render_source_section(source: str, entry: Dict[str, Any]) -> str:
    lines = [f"## {source}", "", _format_status_line(source, entry), _format_filters_line(entry)]
    fields = entry.get("fields")
    if fields:
        rendered = ", ".join(f"`{name}`" for name in fields)
        lines.append(f"- **Fields:** {rendered}")
    note = entry.get("note")
    if note:
        lines.append(f"- **Note:** {note}")
    lines.append("")
    return "\n".join(lines)


_HEADER = """# Data dictionary — Guaraci sources

Generated by `scripts/sample_sources.py` (live sampling with tiny windows) +
`guaraci/data/field_dictionary.json` (machine-readable, consumed by
`guaraci fetch fields <source>`). **Point-in-time** snapshot — re-run the script
to refresh.

- **Filters** = arguments a user can pass (also live via `guaraci fetch schema <source>`).
- **Fields** = output column names from a real sample (`ok` rows below).
- {total} sources cataloged; {ok_count} sampled with real field names.

## Caveats (honest)

{caveats}

## Legend

`ok` = sampled, fields captured · `empty`/`error`/`needs_credential` = see note ·
`filters_only` = not sampled.
"""


def _render_caveats(data: Dict[str, Dict[str, Any]]) -> str:
    bullets = []
    still_pending = []
    for source in sorted(data):
        entry = data[source]
        status = entry.get("status")
        note = entry.get("note")
        if status in ("empty", "error", "needs_credential") and note:
            bullets.append(f"- `{source}` ({status}): {note}")
        elif status == "filters_only":
            still_pending.append(source)
    if still_pending:
        rendered = ", ".join(f"`{s}`" for s in still_pending)
        bullets.append(f"- {len(still_pending)} source(s) still `filters_only` (not yet field-sampled): {rendered}")
    if not bullets:
        return "None — every source has a captured status beyond `filters_only`."
    return "\n".join(bullets)


def render_data_dictionary_md(data: Dict[str, Dict[str, Any]]) -> str:
    total = len(data)
    ok_count = sum(1 for entry in data.values() if entry.get("status") == "ok")
    header = _HEADER.format(total=total, ok_count=ok_count, caveats=_render_caveats(data))
    sections = [render_source_section(source, data[source]) for source in sorted(data)]
    return header + "\n" + "\n".join(sections)
